working solution
mludeiro/training-go-clients pull request #2
Opened 2021-12-22 18:32 UTC by martinpl1989

1st pull request

2021-12-22 18:43 UTC, pabloamura requested changes

2021-12-22 18:43 UTC, pabloamura commented on entity/client.go
> +	HasDebt bool   ``
If we add HasDebt here, does Gorm create it as a field in the database? If so, this field should actually be removed, since the idea is that it comes dynamically from the other microservice, at least for now.

2021-12-22 19:03 UTC, martinpl1989 commented on entity/client.go
> +	HasDebt bool   ``
That's correct. Removed field from db (ignored, actually). The logic to make this field dynamic would be made when the other microservice is ready

2021-12-23 12:19 UTC, pabloamura approved these changes

2021-12-23 13:31 UTC, merged